// Generated by scripts/gen_soc_pkg.py from config/memory.yml.
// Do not edit this file directly.
package soc_pkg;
  localparam int unsigned SOC_CLOCK_HZ = 50000000;
  localparam logic [31:0] SOC_RESET_PC = 32'h3000_0000;

  localparam logic [31:0] SOC_FLASH_BASE = 32'h3000_0000;
  localparam logic [31:0] SOC_FLASH_SIZE = 32'h0100_0000;

  localparam logic [31:0] SOC_PSRAM_BASE = 32'hC000_0000;
  localparam logic [31:0] SOC_PSRAM_SIZE = 32'h0080_0000;

  localparam logic [31:0] SOC_CLINT_BASE = 32'h0201_0000;
  localparam logic [31:0] SOC_CLINT_SIZE = 32'h0001_0000;

  localparam logic [31:0] SOC_PLIC_BASE = 32'h0C00_0000;
  localparam logic [31:0] SOC_PLIC_SIZE = 32'h0040_0000;

  localparam logic [31:0] SOC_UART0_BASE = 32'h1000_0000;
  localparam logic [31:0] SOC_UART0_SIZE = 32'h0000_1000;
  localparam int unsigned SOC_UART0_IRQ = 2;

  localparam logic [31:0] SOC_RCU_BASE = 32'h1000_2000;
  localparam logic [31:0] SOC_RCU_SIZE = 32'h0000_1000;

  localparam logic [31:0] SOC_GPIO0_BASE = 32'h1010_0000;
  localparam logic [31:0] SOC_GPIO0_SIZE = 32'h0000_1000;
  localparam int unsigned SOC_GPIO0_IRQ = 3;

  localparam logic [31:0] SOC_BOOTROM_BASE = SOC_FLASH_BASE;

  localparam int unsigned SOC_IRQ_UART0 = 2;
  localparam int unsigned SOC_IRQ_GPIO0 = 3;
  localparam int unsigned SOC_IRQ_SOFTWARE = 4;
  localparam int unsigned SOC_IRQ_EXTERNAL = 5;

endpackage
