+incdir+../../hw/include
+incdir+../../hw/common/rtl
+incdir+../../hw/common/rtl/cdc
+incdir+../../hw/common/rtl/interface
+incdir+../../hw/common/rtl/tech
+incdir+../../hw/ip/rcu/rtl
+incdir+../../hw/ip/uart16550/rtl
+incdir+../../hw/ip/spi/legacy_apb/rtl
+incdir+../../hw/ip/gpio/rtl
+incdir+../../hw/ip/clint/rtl
+incdir+../../hw/ip/plic/rtl
+define+__VERILOG__
+define+USE_REAL_RCU
+define+USE_REAL_GPIO
+define+USE_REAL_CLINT
+define+USE_REAL_PLIC
../../hw/include/soc_pkg.sv
../../hw/common/rtl/config.svh
../../hw/common/rtl/utils/xchecker.sv
../../hw/common/rtl/cdc/cdc_sync.sv
../../hw/common/rtl/cdc/cdc_2phase.sv
../../hw/common/rtl/clkrst/clk_int_div.sv
../../hw/common/rtl/clkrst/rst_sync.sv
../../hw/common/rtl/clkrst/counter.sv
../../hw/common/rtl/tech/stdcell.sv
../../hw/common/rtl/utils/fifo.sv
../../hw/common/rtl/utils/register.sv
../../hw/common/rtl/utils/edge_det.sv
../../hw/common/rtl/utils/lfsr.sv
../../hw/ip/core/NPC-bstage.sv
../../hw/soc/top/asic_top.v
../../hw/soc/top/frame_reference_top.sv
../../hw/soc/top/apb_delayer.sv
../../hw/soc/top/apb4_flat_stubs.sv
../../hw/ip/rcu/rtl/rcu_core.sv
../../hw/ip/rcu/rtl/apb4_rcu.sv
../../hw/ip/clint/rtl/apb4_clint.sv
../../hw/ip/plic/rtl/plic_gateway.sv
../../hw/ip/plic/rtl/prio_tree.sv
../../hw/ip/plic/rtl/plic_core.sv
../../hw/ip/plic/rtl/apb4_plic.sv
../../hw/ip/gpio/rtl/apb4_gpio.sv
../../hw/ip/spi/legacy_apb/rtl/spi_clgen.v
../../hw/ip/spi/legacy_apb/rtl/spi_shift.v
../../hw/ip/spi/legacy_apb/rtl/spi_top.v
../../hw/ip/spi/legacy_apb/rtl/spi_top_apb.v
../../hw/ip/uart16550/rtl/raminfr.v
../../hw/ip/uart16550/rtl/uart_sync_flops.v
../../hw/ip/uart16550/rtl/uart_rfifo.v
../../hw/ip/uart16550/rtl/uart_tfifo.v
../../hw/ip/uart16550/rtl/uart_receiver.v
../../hw/ip/uart16550/rtl/uart_transmitter.v
../../hw/ip/uart16550/rtl/uart_regs.v
../../hw/ip/uart16550/rtl/uart_top_apb.v
../../hw/ip/flash/model/flash.v
../../hw/ip/psram/model/esp_psram64h/ESP_PSRAM64H.sv
../../hw/ip/psram/model/esp_psram64h/psram_core.sv
../../hw/ip/psram/model/esp_psram64h/psram.sv
